# https://github.com/gemini-testing/gemini/blob/v3.0.2/doc/config.md
rootUrl: http://localhost:9000

browsers:
  Firefox:
    desiredCapabilities:
      browserName: firefox
      # https://ftp.mozilla.org/pub/firefox/releases/46.0.1/linux-x86_64/en-US/
      # DEV: We hardcode this filepath due to Firefox binary annoyancs on our host machine
      firefox_binary: /home/find-work/Downloads/firefox/firefox-46.0.1/firefox

    # Default to large screen as our window size
    windowSize: 1024x1600

    # Restrict to 1 suite per session to prevent issues like mouse down sticking
    sessionsPerBrowser: 1
    suitesPerSession: 1
    # DEV: We can speed up tests overall by using the following but it breaks on `:focus` and similar tests
    # sessionsPerBrowser: 5
    # suitesPerSession: 10
