rootUrl: http://localhost:9000

browsers:
  Firefox:
    desiredCapabilities:
      browserName: firefox
      # DEV: We hardcode this filepath due to Firefox binary annoyancs on our host machine
      firefox_binary: /home/find-work/Downloads/firefox/firefox-46.0.1/firefox

    # Default to large screen as our window size
    windowSize: 1024x1600

    # Restrict to 1 suite per session to prevent issues like mouse down sticking
    suitesPerSession: 1
